SELECT MONTHS_BETWEEN(BIRTH_DATE, SYSDATE),
BIRTH_DATE,
ADD_MONTHS(SYSDATE, MONTHS_BETWEEN(SYSDATE, BIRTH_DATE)),
ADD_MONTHS(SYSDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, BIRTH_DATE))),
ADD_MONTHS(SYSDATE, ROUND(MONTHS_BETWEEN(SYSDATE, BIRTH_DATE)))
FROM TEMP;