SELECT A.EMP_ID "사번", A.EMP_NAME "이름",
A.BIRTH_DATE "생일", COUNT(B.BIRTH_DATE) "생일 빠른 사람 수"
FROM TEMP A, TEMP B
WHERE B.BIRTH_DATE(+) < A.BIRTH_DATE
GROUP BY A.EMP_ID, A.EMP_NAME, A.BIRTH_DATE
ORDER BY COUNT(B.BIRTH_DATE);