SELECT TO_CHAR(SYSDATE, 'YY/MM/DD') DATE1,

TO_CHAR(SYSDATE, 'YYYY.MM.DD') DATE2,

TO_CHAR(SYSDATE, 'Month DD.YYYY') DATE3,

TO_CHAR(SYSDATE, 'DY DD MON YY') DATE4,

TO_CHAR(SYSDATE, 'Day Mon DD') DATE5

FROM DUAL;