SELECT A.EMP_ID, A.EMP_NAME, B.DEPT_CODE, B.DEPT_NAME,
C.DEPT_CODE, C.DEPT_NAME, D.EMP_ID, D.EMP_NAME
FROM TEMP A, TDEPT B, TDEPT C, TEMP D
WHERE B.DEPT_CODE = A.DEPT_CODE
AND C.DEPT_CODE = B.PARENT_DEPT
AND C.DEPT_CODE = 'CA0001'
AND D.EMP_ID = C.BOSS_ID;