CREATE VIEW TEMP_VIEW
AS
SELECT A.EMP_ID AS "사번",
A.EMP_NAME AS "성명",
A.BIRTH_DATE AS "생일",
A.DEPT_CODE AS "부서",
B.DEPT_NAME AS "부서명",
A.SALARY AS "연봉",
A.LEV AS "직급"
FROM TEMP A, TDEPT B
WHERE B.DEPT_CODE = A.DEPT_CODE
AND A.EMP_TYPE = '정규'