SELECT A.LEV, A.BOSS, B.EMP_NAME
FROM TEMP B,
(SELECT LEVEL LEV, LPAD(BOSS_ID, LEVEL * 5, ' ') BOSS
FROM TDEPT
CONNECT BY PRIOR DEPT_CODE = PARENT_DEPT
START WITH DEPT_CODE = '000000'
) A
WHERE B.EMP_ID (+) = A.BOSS;